services:
    - type: web
      name: allgpt-service
      env: docker
      plan: free
      healthCheckPath: /api/providers/status
      envVars:
         - key: PORT
        value: 5500
      - key: NODE_ENV
        value: production
