services:
    - type: web
      name: allgpt-service
      env: docker
      plan: free
      healthCheckPath: /api/providers/status
      envVars:
          - key: NODE_ENV
            value: production
          - key: PORT
            value: 3000
