services:
    - type: web
      name: allgpt-service
      env: docker
      buildCommand: npm install && pip install -r requirements.txt
      startCommand: node index.js
      envVars:
          - key: PORT
            value: 3000
